---
- name: "UdaPeople Configurations"
  hosts: web
  user: ubuntu 
  environment:
    # Get the environment variables from CircleCI and add to the instance
    TYPEORM_MIGRATIONS: "{{ ansible_env.TYPEORM_MIGRATIONS }}"
    TYPEORM_ENTITIES: "{{ ansible_env.TYPEORM_ENTITIES }}"
    TYPEORM_CONNECTION: "{{ ansible_env.TYPEORM_CONNECTION }}"
    TYPEORM_HOST: "{{ ansible_env.TYPEORM_HOST }}"
    TYPEORM_PORT: "{{ ansible_env.TYPEORM_PORT }}"
    TYPEORM_USERNAME: "{{ ansible_env.TYPEORM_USERNAME }}"
    TYPEORM_PASSWORD: "{{ ansible_env.TYPEORM_PASSWORD }}"
    TYPEORM_DATABASE: "{{ ansible_env.TYPEORM_DATABASE }}"
    ENVIRONMENT: "{{ ansible_env.ENVIRONMENT }}"
    #API_URL: "{{ ansible_env.API_URL') }}"
  
  gather_facts: true

  roles:
      - prepare
      - configure-server
      - deploy
