---
- name: "UdaPeople Configurations"
  hosts: web
  user: ubuntu
 
  vars:
    # Get the environment variables from CircleCI and add to the instance
    TYPEORM_MIGRATIONS: "{{ lookup('env','TYPEORM_MIGRATIONS') }}"
    TYPEORM_ENTITIES: "{{ lookup('env','TYPEORM_ENTITIES') }}"
    TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env','TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
    ENVIRONMENT: "{{ lookup('env','ENVIRONMENT') }}"
    #API_URL: "{{ lookup('env','API_URL') }}"
  tasks:
    - debug: msg="{{ TYPEORM_HOST }}"
  gather_facts: true

  roles:
      - prepare
      - configure-server
      - deploy
