---
- name: Copying files from CircleCI to Server
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: Stopping PM2
  ignore_errors: yes
  shell: |
    cd /home/ubuntu/backend
    pm2 stop backend
    pm2 delete backend

- name: Installing node dependencies
  shell: |
    cd /home/ubuntu/backend    
    npm install 

- name: Building node service
  shell: |
    cd /home/ubuntu/backend
    npm run build

- name: Run node migrations and saving to MemStash.io
  shell: |
    cd /home/ubuntu/backend
    npm run migrations > migrations.txt
    curl -H "Content-Type: text/plain" -H "token: e13a6cc4-3f08-4da7-9177-216b218d0341" --request PUT --data $( grep -c "No migrations are pending" migrations.txt ) https://api.memstash.io/values/migration_status


#- name: Run node migrations
#  shell: |
#    cd /home/ubuntu/backend
#    npm run migrations