version: 2.1

jobs:
  create_infrastructure:
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Deploys the Network 
            command: |
              cd .circle/files/
              aws cloudformation deploy \
                --template-file network.yml \
                --stack-name network-stack 
        - run:
            name: Deploys the Backend
            command: |
              cd .circle/files/
              aws cloudformation deploy \
                --template-file backend.yml \
                --stack-name backend-stack
        - run:
            name: Deploys the Cloudfront
            command: |
              cd .circle/files/
              aws cloudformation deploy \
                --template-file cloudfront.yml \
                --stack-name cloudfront-stack
        - run:
            name: Deploys the Frontend
            command: |
              cd .circle/files/
              aws cloudformation deploy \
                --template-file frontend.yml \
                --stack-name frontend-stack

workflows:
      - create_infrastructure