version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "Hello World"

  build-frontend:
    docker:
      - image: circleci/node:13.8.0 
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build Front-End
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0 
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Scan backend dependencies
          command: |
              cd backend
              npm install
              npm audit --audit-level=critical || true

  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: |
              cd frontend
              npm install
              npm run test

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: |
              cd backend
              npm install
              npm run test

  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: |
              cd backend
              npm audit fix --audit-level=critical --force
      - run:
          command: |
              cd frontend
              npm audit fix --audit-level=critical --force

  create_infrastructure:
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Deploys the Network 
            command: |
              cd .circle/files/
              aws cloudformation deploy \
                --template-file network.yml \
                --stack-name network-stack 
        - run:
            name: Deploys the Backend
            command: |
              cd .circle/files/
              aws cloudformation deploy \
                --template-file backend.yml \
                --stack-name backend-stack
        - run:
            name: Deploys the Cloudfront
            command: |
              cd .circle/files/
              aws cloudformation deploy \
                --template-file cloudfront.yml \
                --stack-name cloudfront-stack
        - run:
            name: Deploys the Frontend
            command: |
              cd .circle/files/
              aws cloudformation deploy \
                --template-file frontend.yml \
                --stack-name frontend-stack

workflows:
  build-test-and-approval-deploys:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires:
            - build-frontend
      - test-backend:
          requires:
            - build-backend
      - analyze:
          requires:
            - test-backend
      - create_infrastructure:
          requires:
            - analyze