Description: >
  UdaPeople backend stack.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String
    Default: "InstanceStack"

Resources:  
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: vpc-038b26ff6885a4676
      GroupName: !Sub UdaPeople-${ID}
      GroupDescription: Allow port 22 and port 3000.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3030
          ToPort: 3030
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SubnetId: subnet-0eabbaed33bc83ad7
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: circle-ci
      ImageId: ami-068663a3c619dd892
      Tags:
        - Key: Name
          Value: !Sub backend-${ID}
